### ISSUE TITLE
Support image descriptions

### ISSUE THREAD

**Issue by jmatsushita** [GitbookIO/gitbook-markdown#12]
http://spec.commonmark.org/0.24/#image-description

**Comment by SamyPesse** [comment]
Can you open an issue on https://github.com/GitbookIO/markup-it

We are going to switch parsing to this module.

**Comment by jmatsushita** [comment]
Gitbook 2.4.3 renders such image descriptions as:

```
http://mygitbook.example.org/test/emergencies/example.png%20%22title%20
```

Ok will submit to markup-it even though I don't know yet if it has the same bug!
