### ISSUE TITLE
Several code-block escaping issues remain in 0.4.2

### ISSUE THREAD

**Issue by anthonyfok** [GitbookIO/gitbook-markdown#2]
Hi @SamyPesse,

I am new to GitBook, and I hope I am filing this issue in the right place.  I got the hint from your helpful commit messages related "code block escaping" from 8 days ago leading up to the latest gitbook-markdown 0.4.2.

While trying to build @astaxie’s book https://github.com/astaxie/build-web-application-with-golang, which contains sample code blocks with Go templates with `{{ }}`-enclosed commands similar to nunjucks, I encountered errors like these:

```
$ gitbook --debug build
info: loading book configuration....
warn: you should specify a gitbook version to use in your book.json, for example: 2.x.x 
info: OK 
info: >> 0 plugins loaded 
info: Parsing multilingual book, with 4 lanuages 
info: Preparing language book en 
info: Preparing language book fr 
info: Preparing language book zh 
info: Preparing language book ja 
info: loading book configuration....OK 
info: >> 0 plugins loaded 
info: loading book configuration....OK 
info: >> 0 plugins loaded 
info: loading book configuration....OK 
info: >> 0 plugins loaded 
info: loading book configuration....OK 
info: >> 0 plugins loaded 
info: start generation with website generator 
info: clean website generator
info: OK 
info: start generation with website generator 
info: clean website generatorOK 

Template render error: unexpected token: . (In file '13.5.md', Line 281, Column 10)
Template render error: unexpected token: .
    at Error.exports.TemplateError (/home/foka/.gitbook/versions/2.0.1/node_modules/nunjucks/src/lib.js:51:19)
    at Object.extend.fail (/home/foka/.gitbook/versions/2.0.1/node_modules/nunjucks/src/parser.js:64:15)
    at Object.extend.parsePrimary (/home/foka/.gitbook/versions/2.0.1/node_modules/nunjucks/src/parser.js:947:18)
    at Object.extend.parseUnary (/home/foka/.gitbook/versions/2.0.1/node_modules/nunjucks/src/parser.js:882:25)
    at Object.extend.parsePow (/home/foka/.gitbook/versions/2.0.1/node_modules/nunjucks/src/parser.js:856:25)
    at Object.extend.parseMod (/home/foka/.gitbook/versions/2.0.1/node_modules/nunjucks/src/parser.js:844:25)
    at Object.extend.parseFloorDiv (/home/foka/.gitbook/versions/2.0.1/node_modules/nunjucks/src/parser.js:832:25)
    at Object.extend.parseDiv (/home/foka/.gitbook/versions/2.0.1/node_modules/nunjucks/src/parser.js:820:25)
    at Object.extend.parseMul (/home/foka/.gitbook/versions/2.0.1/node_modules/nunjucks/src/parser.js:808:25)
    at Object.extend.parseSub (/home/foka/.gitbook/versions/2.0.1/node_modules/nunjucks/src/parser.js:796:25)
```

I was able to get a particular Markdown file to build by removing all trailing whitespaces: https://github.com/astaxie/build-web-application-with-golang/pull/463

But it turns out there are more cases where it fails, and @astaxie and I agree that this is something that should be fixed in GitBook (or gitbook-markdown).

When you have time, please `git clone https://github.com/astaxie/build-web-application-with-golang.git` and test it with the latest `gitbook`.  While the English and French versions build fine, you will likely encounter many errors with the Chinese version, not due to the CJK characters, but rather due to different whitespaces.  In my brief testing on Linux (Ubuntu), Go templates in code blocks in the Markdown files would trigger an error in the following circumstances:

* Files with CRLF-terminated lines (from DOS/Windows)
* A tab-indented code block with an empty line, where that empty line is also tab-indented, e.g.

    ```
        <h1>{{.Post.Title}}</h1>⏎
        {{.Post.Created}}<br/>⏎
        ⏎
        {{.Post.Content}}⏎
```
* Extraneous tab on a line right before a fenced code block (?), or perhaps extraneous tab after a <code>&#96;&#96;&#96;</code> right at the end of a fence, as in https://github.com/astaxie/build-web-application-with-golang/pull/463.  While I would agree that leaving such extraneous whitespaces behind is sloppy :wink:, it would be ideal if GitBook can handle such cases especially if GFM and `kramed` can too.

Many thanks!

Anthony

**Comment by SamyPesse** [comment]
Thanks you for reporting this (with all needed details :) ).

I'll take a look at this issue as soon as possible. The first will be to add more unit tests for codeblocks escaping (https://github.com/GitbookIO/gitbook-markdown/blob/master/test/page.js#L23).

@anthonyfok I'll commit some tests as soon as possible so that you can confirm it covers all your issue.

@AaronO any idea how we can improve and fix this ?

**Comment by eibrahim** [comment]
Is this fixed?  I am having the same issue with handlebar code blocks that start with `{{`

**Comment by StevenRoan** [comment]
Same here still happened in version 1.0.1 when I'm trying to write sth related to meteor

**Comment by snowdream** [comment]
Same here.
