### ISSUE TITLE
Header's ID is generated urlencoded

### ISSUE THREAD

**Issue by alexandre-mbm** [GitbookIO/gitbook-markdown#6]
But on GitHub no, and this does more sense.

PS.: there are some small differences between the GitHub and Gitbook results.

**Comment by alexandre-mbm** [comment]
But there are some small differences between the GitHub and Gitbook results.

**Comment by alexandre-mbm** [comment]
I consider this as a Gitbook's bug. It is putting the URL encoded already in the HTML code.

**Comment by SamyPesse** [comment]
This will be fixed in the next release of gitbook (we'll normalize ID for markdown and asciidoc in gitbook core, in the same way as github).

**Comment by RyanZim** [comment]
> we'll normalize ID for markdown and asciidoc in gitbook core, in the same way as github

@SamyPesse Just to clarify, does this mean that gitbook now functions the same way as github?

Just trying to see if https://github.com/thlorenz/anchor-markdown-header/issues/25 is invalid.
